using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Windows.Forms;
using System.Xml.Serialization;

public class Student { public string Id=Guid.NewGuid().ToString(); public string Name=""; public string Course=""; public string State="훈련 중"; }
public class Attendance { public string StudentId=""; public string Day=""; public string Status=""; public string Note=""; }
public class Session { public string Id=Guid.NewGuid().ToString(); public string StudentId=""; public string Day=""; public string Content=""; public string Follow=""; }
public class Records { public List<Student> Students=new List<Student>(); public List<Attendance> Attendance=new List<Attendance>(); public List<Session> Sessions=new List<Session>(); }
public static class Storage {
 public static string Folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"VocationalTrainingManager");
 public static string FileName { get { return Path.Combine(Folder,"records.dat"); } }
 public static byte[] Encode(Records r) { using(var m=new MemoryStream()) { new XmlSerializer(typeof(Records)).Serialize(m,r); return ProtectedData.Protect(m.ToArray(),null,DataProtectionScope.CurrentUser); } }
 public static Records Decode(byte[] b) { using(var m=new MemoryStream(ProtectedData.Unprotect(b,null,DataProtectionScope.CurrentUser))) return (Records)new XmlSerializer(typeof(Records)).Deserialize(m); }
 public static Records Load() { return File.Exists(FileName)?Decode(File.ReadAllBytes(FileName)):new Records(); }
 public static void Save(Records r) {
  Directory.CreateDirectory(Folder); string temp=FileName+".tmp"; File.WriteAllBytes(temp,Encode(r));
  if(File.Exists(FileName)) File.Replace(temp,FileName,FileName+".previous"); else File.Move(temp,FileName);
 }
}
public class MainForm:Form {
 Records records; DataGridView students=new DataGridView(), attendance=new DataGridView(), sessions=new DataGridView();
 ComboBox person=new ComboBox(); TextBox search=new TextBox(); DateTimePicker day=new DateTimePicker(); Label message=new Label(); string attendanceDay=""; bool dirty=false, refreshing=false; TabControl tabs=new TabControl(); TabPage attendancePage;
 public MainForm(Records data) {
  records=data; Text="훈련생 출결 · 상담 관리"; Size=new Size(1140,780); MinimumSize=new Size(920,650); StartPosition=FormStartPosition.CenterScreen; Font=new Font("맑은 고딕",10);
  var root=new TableLayoutPanel { Dock=DockStyle.Fill,RowCount=4,ColumnCount=1,Padding=new Padding(20) }; root.RowStyles.Add(new RowStyle(SizeType.Absolute,62));root.RowStyles.Add(new RowStyle(SizeType.Absolute,44));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,36)); Controls.Add(root);
  var title=new Label { Text="훈련생 관리\n출결과 상담 기록을 한곳에서 확인하세요.",Dock=DockStyle.Fill,Font=new Font("맑은 고딕",13,FontStyle.Bold) };root.Controls.Add(title,0,0);
  var top=Bar();top.Controls.Add(Button("백업 저장",Backup));top.Controls.Add(Button("백업 복원",Restore));top.Controls.Add(Button("가상 데이터 추가",Demo));top.Controls.Add(new Label{Text="자료 저장: 이 PC의 현재 Windows 계정",AutoSize=true,Padding=new Padding(15,8,0,0)});root.Controls.Add(top,0,1);
  tabs.Dock=DockStyle.Fill;root.Controls.Add(tabs,0,2); message.Dock=DockStyle.Fill;message.Padding=new Padding(0,8,0,0);root.Controls.Add(message,0,3);
  var p1=Page("훈련생"); var b1=Bar();b1.Controls.Add(Button("훈련생 등록",delegate{EditStudent(false);}));b1.Controls.Add(Button("선택 정보 수정",delegate{EditStudent(true);}));p1.Controls.Add(students);p1.Controls.Add(b1);Grid(students,true);students.Columns.Add("Id","ID");students.Columns[0].Visible=false;students.Columns.Add("Name","이름");students.Columns.Add("Course","훈련과정");students.Columns.Add("State","상태");
  attendancePage=Page("출결"); var b2=Bar();day.Format=DateTimePickerFormat.Short;day.Width=140;b2.Controls.Add(day);b2.Controls.Add(Button("미입력 → 출석",delegate{foreach(DataGridViewRow r in attendance.Rows) if(Convert.ToString(r.Cells[2].Value)=="미입력") r.Cells[2].Value="출석";}));b2.Controls.Add(Button("출결 저장",SaveAttendance));attendancePage.Controls.Add(attendance);attendancePage.Controls.Add(b2);Grid(attendance,false);
  attendance.Columns.Add("Id","ID");attendance.Columns[0].Visible=false;attendance.Columns.Add("Name","이름");attendance.Columns[1].ReadOnly=true;var status=new DataGridViewComboBoxColumn{Name="Status",HeaderText="출결",FlatStyle=FlatStyle.Flat};status.Items.AddRange("미입력","출석","지각","조퇴","결석","공결");attendance.Columns.Add(status);attendance.Columns.Add("Note","사유 · 메모");
  attendance.CellValueChanged+=delegate{if(!refreshing)dirty=true;};attendance.CurrentCellDirtyStateChanged+=delegate{if(attendance.IsCurrentCellDirty)attendance.CommitEdit(DataGridViewDataErrorContexts.Commit);};
  DateTime previous=day.Value.Date;day.ValueChanged+=delegate{if(refreshing)return;if(!ConfirmPending()){refreshing=true;day.Value=previous;refreshing=false;return;} previous=day.Value.Date;RefreshAttendance();};
  var p3=Page("상담 기록");var b3=Bar();person.DropDownStyle=ComboBoxStyle.DropDownList;person.Width=235;search.Width=170;b3.Controls.Add(person);b3.Controls.Add(new Label{Text="내용 검색",AutoSize=true,Padding=new Padding(8,8,0,0)});b3.Controls.Add(search);b3.Controls.Add(Button("상담 작성",delegate{EditSession(false);}));b3.Controls.Add(Button("보기 · 수정",delegate{EditSession(true);}));p3.Controls.Add(sessions);p3.Controls.Add(b3);Grid(sessions,true);sessions.Columns.Add("Id","ID");sessions.Columns[0].Visible=false;sessions.Columns.Add("Day","상담일");sessions.Columns.Add("Name","훈련생");sessions.Columns.Add("Content","상담 내용");sessions.Columns.Add("Follow","후속 조치");person.SelectedIndexChanged+=delegate{RefreshSessions();};search.TextChanged+=delegate{RefreshSessions();};sessions.CellDoubleClick+=delegate(object sender,DataGridViewCellEventArgs e){if(e.RowIndex>=0)EditSession(true);};
  tabs.Selecting+=delegate(object sender,TabControlCancelEventArgs e){if(tabs.SelectedTab==attendancePage&&!ConfirmPending())e.Cancel=true;};FormClosing+=delegate(object sender,FormClosingEventArgs e){if(!ConfirmPending())e.Cancel=true;};RefreshAll();
 }
 TabPage Page(string name){var p=new TabPage(name){Padding=new Padding(12)};tabs.TabPages.Add(p);return p;}
 static FlowLayoutPanel Bar(){return new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,WrapContents=false};}
 static Button Button(string text,Action action){var b=new Button{Text=text,AutoSize=true,Height=34,MinimumSize=new Size(110,34),Margin=new Padding(0,0,8,0)};b.Click+=delegate{try{action();}catch(Exception ex){MessageBox.Show("처리하지 못했습니다.\n"+ex.Message,"확인",MessageBoxButtons.OK,MessageBoxIcon.Error);}};return b;}
 static void Grid(DataGridView g,bool read){g.Dock=DockStyle.Fill;g.BackgroundColor=Color.White;g.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;g.AllowUserToAddRows=false;g.AllowUserToDeleteRows=false;g.ReadOnly=read;g.RowHeadersVisible=false;g.SelectionMode=DataGridViewSelectionMode.FullRowSelect;g.MultiSelect=false;g.AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.AllCells;g.DefaultCellStyle.WrapMode=DataGridViewTriState.True;g.ColumnHeadersHeight=36;g.BorderStyle=BorderStyle.FixedSingle;}
 string SelectedId(DataGridView g){return g.CurrentRow==null?null:Convert.ToString(g.CurrentRow.Cells[0].Value);}
 bool Commit(Action change){Records snapshot=Storage.Decode(Storage.Encode(records));try{change();Storage.Save(records);message.Text="저장 완료 · "+DateTime.Now.ToString("HH:mm:ss");return true;}catch(Exception ex){records=snapshot;MessageBox.Show("저장하지 못했습니다. 입력 내용을 확인하고 다시 시도하세요.\n"+ex.Message);return false;}}
 bool ConfirmPending(){attendance.EndEdit();if(!dirty)return true;var answer=MessageBox.Show("변경한 출결을 저장할까요?","출결 저장",MessageBoxButtons.YesNoCancel);if(answer==DialogResult.Cancel)return false;if(answer==DialogResult.Yes){SaveAttendance();return !dirty;}dirty=false;RefreshAttendance();return true;}
 void RefreshAll(){students.Rows.Clear();foreach(var s in records.Students.OrderBy(x=>x.Name))students.Rows.Add(s.Id,s.Name,s.Course,s.State);string selected=(person.SelectedItem as PersonItem)==null?"":((PersonItem)person.SelectedItem).Id;person.Items.Clear();person.Items.Add(new PersonItem("","전체 훈련생"));foreach(var s in records.Students.OrderBy(x=>x.Name))person.Items.Add(new PersonItem(s.Id,s.Name+" · "+s.Course));person.SelectedIndex=0;for(int i=0;i<person.Items.Count;i++)if(((PersonItem)person.Items[i]).Id==selected)person.SelectedIndex=i;RefreshAttendance();RefreshSessions();}
 void RefreshAttendance(){refreshing=true;attendance.Rows.Clear();string date=day.Value.ToString("yyyy-MM-dd");attendanceDay=date;foreach(var s in records.Students.OrderBy(x=>x.Name)){var a=records.Attendance.FirstOrDefault(x=>x.StudentId==s.Id&&x.Day==date);if(s.State!="훈련 중"&&a==null)continue;attendance.Rows.Add(s.Id,s.Name,a==null?"미입력":a.Status,a==null?"":a.Note);}refreshing=false;dirty=false;}
 void SaveAttendance(){attendance.EndEdit();string date=attendanceDay;if(Commit(delegate{foreach(DataGridViewRow row in attendance.Rows){string id=Convert.ToString(row.Cells[0].Value),status=Convert.ToString(row.Cells[2].Value);records.Attendance.RemoveAll(x=>x.StudentId==id&&x.Day==date);if(status!="미입력")records.Attendance.Add(new Attendance{StudentId=id,Day=date,Status=status,Note=Convert.ToString(row.Cells[3].Value)});}}))dirty=false;}
 void RefreshSessions(){if(sessions.Columns.Count==0)return;sessions.Rows.Clear();var p=person.SelectedItem as PersonItem;string id=p==null?"":p.Id;string q=search.Text.Trim();foreach(var s in records.Sessions.Where(x=>(id==""||x.StudentId==id)&&(q==""||x.Content.IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0||x.Follow.IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0)).OrderByDescending(x=>x.Day)){var st=records.Students.FirstOrDefault(x=>x.Id==s.StudentId);sessions.Rows.Add(s.Id,s.Day,st==null?"":st.Name,s.Content,s.Follow);}}
 void EditStudent(bool edit){if(!ConfirmPending())return;Student s=edit?records.Students.FirstOrDefault(x=>x.Id==SelectedId(students)):new Student();if(s==null){MessageBox.Show("훈련생을 선택하세요.");return;}using(var f=new Entry("훈련생 정보")){var name=f.TextField("이름 *",s.Name,false);var course=f.TextField("훈련과정 *",s.Course,false);var state=f.Choice("상태",new object[]{"훈련 중","수료","중도 종료"},s.State);f.ValidateInput=delegate{return name.Text.Trim()!=""&&course.Text.Trim()!="";};if(f.ShowDialog(this)!=DialogResult.OK)return;if(Commit(delegate{s.Name=name.Text.Trim();s.Course=course.Text.Trim();s.State=state.Text;if(!edit)records.Students.Add(s);} ))RefreshAll();}}
 void EditSession(bool edit){if(!ConfirmPending())return;if(records.Students.Count==0){MessageBox.Show("훈련생을 먼저 등록하세요.");return;}Session s=edit?records.Sessions.FirstOrDefault(x=>x.Id==SelectedId(sessions)):new Session{Day=DateTime.Today.ToString("yyyy-MM-dd")};if(s==null){MessageBox.Show("상담 기록을 선택하세요.");return;}using(var f=new Entry(edit?"상담 기록 보기 · 수정":"상담 기록 작성")){var options=records.Students.OrderBy(x=>x.Name).Select(x=>(object)new PersonItem(x.Id,x.Name+" · "+x.Course)).ToArray();var who=f.Choice("훈련생 *",options,null);string id=edit?s.StudentId:((person.SelectedItem as PersonItem)==null?"":((PersonItem)person.SelectedItem).Id);for(int i=0;i<who.Items.Count;i++)if(((PersonItem)who.Items[i]).Id==id)who.SelectedIndex=i;var date=f.DateField("상담일",DateTime.Parse(s.Day));var content=f.TextField("상담 내용 *",s.Content,true);var follow=f.TextField("후속 조치",s.Follow,true);f.ValidateInput=delegate{return content.Text.Trim()!="";};if(f.ShowDialog(this)!=DialogResult.OK)return;if(Commit(delegate{s.StudentId=((PersonItem)who.SelectedItem).Id;s.Day=date.Value.ToString("yyyy-MM-dd");s.Content=content.Text.Trim();s.Follow=follow.Text.Trim();if(!edit)records.Sessions.Add(s);} ))RefreshSessions();}}
 void Backup(){if(!ConfirmPending())return;using(var d=new SaveFileDialog{Filter="암호화 백업 (*.vtbackup)|*.vtbackup",FileName="훈련생백업_"+DateTime.Now.ToString("yyyyMMdd_HHmmss")+".vtbackup"}){if(d.ShowDialog()!=DialogResult.OK)return;File.WriteAllBytes(d.FileName,Storage.Encode(records));MessageBox.Show("백업했습니다. 이 백업은 현재 Windows 계정에서만 복원할 수 있습니다.");}}
 void Restore(){if(!ConfirmPending())return;using(var d=new OpenFileDialog{Filter="암호화 백업 (*.vtbackup)|*.vtbackup"}){if(d.ShowDialog()!=DialogResult.OK)return;Records imported=Storage.Decode(File.ReadAllBytes(d.FileName));if(MessageBox.Show("현재 자료를 백업 내용으로 교체합니다.\n훈련생 "+imported.Students.Count+"명 / 출결 "+imported.Attendance.Count+"건 / 상담 "+imported.Sessions.Count+"건\n계속할까요?","복원 확인",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;Directory.CreateDirectory(Storage.Folder);File.WriteAllBytes(Path.Combine(Storage.Folder,"복원전_"+DateTime.Now.ToString("yyyyMMdd_HHmmssfff")+".vtbackup"),Storage.Encode(records));if(Commit(delegate{records=imported;}))RefreshAll();}}
 void Demo(){if(!ConfirmPending())return;if(records.Students.Any()){MessageBox.Show("가상 데이터는 훈련생이 없는 상태에서만 추가할 수 있습니다.");return;}if(Commit(delegate{var s=new Student{Name="가상 훈련생",Course="사무행정(예시)"};records.Students.Add(s);records.Sessions.Add(new Session{StudentId=s.Id,Day=DateTime.Today.ToString("yyyy-MM-dd"),Content="[가상 예시] 실습 과제 진행 상황을 함께 확인함.",Follow="다음 상담에서 과제 수행 상황 확인"});}))RefreshAll();}
}
public class PersonItem {public string Id,Name;public PersonItem(string id,string name){Id=id;Name=name;}public override string ToString(){return Name;}}
public class Entry:Form {
 FlowLayoutPanel body=new FlowLayoutPanel();public Func<bool> ValidateInput;
 public Entry(string title){Text=title;Size=new Size(670,700);MinimumSize=new Size(560,500);StartPosition=FormStartPosition.CenterParent;Font=new Font("맑은 고딕",10);body.Dock=DockStyle.Fill;body.FlowDirection=FlowDirection.TopDown;body.WrapContents=false;body.AutoScroll=true;body.Padding=new Padding(15);Controls.Add(body);var bar=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=52,Padding=new Padding(15,5,0,0)};var save=new Button{Text="저장",Width=100,Height=32};var cancel=new Button{Text="취소",Width=100,Height=32,DialogResult=DialogResult.Cancel};save.Click+=delegate{if(ValidateInput!=null&&!ValidateInput()){MessageBox.Show("별표(*)가 있는 항목을 입력하세요.");return;}DialogResult=DialogResult.OK;};bar.Controls.Add(save);bar.Controls.Add(cancel);Controls.Add(bar);CancelButton=cancel;}
 void LabelFor(string text){body.Controls.Add(new Label{Text=text,AutoSize=true,Margin=new Padding(0,9,0,5)});}
 public TextBox TextField(string label,string value,bool multi){LabelFor(label);var t=new TextBox{Text=value,Width=590,Multiline=multi,Height=multi?145:30,ScrollBars=multi?ScrollBars.Vertical:ScrollBars.None,MaxLength=multi?50000:200};body.Controls.Add(t);return t;}
 public ComboBox Choice(string label,object[] values,string value){LabelFor(label);var c=new ComboBox{Width=590,DropDownStyle=ComboBoxStyle.DropDownList};c.Items.AddRange(values);if(c.Items.Count>0)c.SelectedIndex=0;if(value!=null)c.SelectedItem=value;body.Controls.Add(c);return c;}
 public DateTimePicker DateField(string label,DateTime value){LabelFor(label);var d=new DateTimePicker{Format=DateTimePickerFormat.Short,Value=value,Width=200};body.Controls.Add(d);return d;}
}
public static class Program {
 [STAThread] public static void Main(string[] args){
  if(args.Contains("--preview")){Application.EnableVisualStyles();var r=new Records();r.Students.Add(new Student{Name="가상 훈련생",Course="사무행정(예시)"});using(var stream=new MemoryStream()){new XmlSerializer(typeof(Records)).Serialize(stream,r);stream.Position=0;if(((Records)new XmlSerializer(typeof(Records)).Deserialize(stream)).Students[0].Name!="가상 훈련생")throw new Exception("Serialization failed");}using(var f=new MainForm(r)){f.Opacity=0;f.ShowInTaskbar=false;f.Show();Application.DoEvents();using(var b=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(b,new Rectangle(0,0,f.Width,f.Height));b.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"화면예시.png"));}}return;} if(args.Contains("--self-test")){try{SelfTest();}catch(Exception ex){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"self-test-result.txt"),ex.ToString());Environment.ExitCode=1;}return;}
  bool created;using(var mutex=new System.Threading.Mutex(true,"Local\\VocationalTrainingManager",out created)){if(!created){MessageBox.Show("프로그램이 이미 실행 중입니다.");return;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{Application.Run(new MainForm(Storage.Load()));}catch(Exception ex){MessageBox.Show("프로그램을 열지 못했습니다. 기존 자료는 덮어쓰지 않았습니다.\n"+ex.Message,"훈련생 관리");}}
 }
 static void SelfTest(){string temp=Path.Combine(Path.GetTempPath(),"TrainingManagerTest_"+Guid.NewGuid());Storage.Folder=temp;try{var r=new Records();var s=new Student{Name="시험 훈련생",Course="테스트"};r.Students.Add(s);r.Attendance.Add(new Attendance{StudentId=s.Id,Day="2026-09-08",Status="출석"});r.Sessions.Add(new Session{StudentId=s.Id,Day="2026-09-08",Content="상담\n두 번째 줄",Follow="확인"});Storage.Save(r);var loaded=Storage.Load();if(loaded.Students[0].Name!=s.Name||loaded.Sessions[0].Content!=r.Sessions[0].Content)throw new Exception("Roundtrip failed");loaded.Attendance[0].Status="지각";Storage.Save(loaded);if(Storage.Load().Attendance[0].Status!="지각"||!File.Exists(Storage.FileName+".previous"))throw new Exception("Update failed");if(Storage.Decode(File.ReadAllBytes(Storage.FileName+".previous")).Attendance[0].Status!="출석")throw new Exception("Backup failed");using(var form=new MainForm(loaded)){form.CreateControl();}File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"self-test-result.txt"),"PASS: encrypted persistence, Korean multiline text, atomic update, previous backup, form construction.");}finally{if(Directory.Exists(temp))Directory.Delete(temp,true);}}
}
